### ISSUE TITLE
new tab issues

### ISSUE THREAD

**Issue by Dialgatrainer02** [noriaku/firefox-monolite#4]
when i try to use any new tab extensions to use this as new tab as well as start page it will break the look and glitch out or wont work and fallback to the blank page. im not using a web server only the local file whats the recommended way to do this?

**Comment by noriaku** [comment]
Hey, I just wrote a section "Setting up Apache" inside [README.md](https://github.com/noriaku/firefox-monolite/blob/main/README.md), I tested it with the [New Tab Override](https://addons.mozilla.org/en-US/firefox/addon/new-tab-override/) extension, and it works perfectly. The problem was that only the index.tml was indexed, so styles were not loaded, working on a local web server the problem disappears.

**Comment by Dialgatrainer02** [comment]
Thank you for the help and the amazing looking thene
